#spring.security.oauth2.client.registration.google.client-id=150100738868-aor930qv6isql8ggrhlmuoaiqkb7shrk.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://bronto.ewi.utwente.nl/
    username: dab_di20212b_85
    password: 2plKsgaKZYuRy6EY
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
