#spring.security.oauth2.client.registration.google.client-id=150100738868-aor930qv6isql8ggrhlmuoaiqkb7shrk.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 2plKsgaKZYuRy6EY
    url: jdbc:postgresql://bronto.ewi.utwente.nl/registration
    username: dab_di20212b_85
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

